name: Build and Push

on:
  push:
    branches:
      - main
      - v*
      - dev*
    paths:
      - "Containerfile"
      - ".github/workflows/release.yml"

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Docker Hub Credentials
        id: check_docker_creds
        run: |
          if [[ -n "${{ secrets.DOCKER_USER }}" && -n "${{ secrets.DOCKER_TOKEN }}" ]]; then
            echo "docker_creds_exist=true" >> $GITHUB_OUTPUT
          else
            echo "docker_creds_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub (if credentials are provided)
        if: steps.check_docker_creds.outputs.docker_creds_exist == 'true'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate Tags
        id: generate_tags
        env:
          IMAGE_REPO: ${{ github.repository_owner }}/cfdns
        run: |
          # GHCR Repository
          GHCR_REPO="ghcr.io/$IMAGE_REPO"

          # Check if the current ref is a tag
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "Detected tag: ${{ github.ref_name }}"
            echo "ghcr_image_tag=$GHCR_REPO:${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "ghcr_image_latest=$GHCR_REPO:latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "ghcr_image_tag=$GHCR_REPO:main" >> $GITHUB_OUTPUT
          else
            echo "ghcr_image_tag=$GHCR_REPO:dev" >> $GITHUB_OUTPUT
          fi

          # Docker Repository
          DOCKER_REPO="docker.io/$IMAGE_REPO"

          # Docker Hub tags (if credentials provided)
          if [[ "${{ steps.check_docker_creds.outputs.docker_creds_exist }}" == "true" ]]; then
            if [[ "${{ github.ref_type }}" == "tag" ]]; then
              echo "docker_image_tag=$DOCKER_REPO:${{ github.ref_name }}" >> $GITHUB_OUTPUT
              echo "docker_image_latest=$DOCKER_REPO:latest" >> $GITHUB_OUTPUT
            elif [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "docker_image_tag=$DOCKER_REPO:main" >> $GITHUB_OUTPUT
            else
              echo "docker_image_tag=$DOCKER_REPO:dev" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          file: Containerfile
          tags: |
            ${{ steps.generate_tags.outputs.ghcr_image_tag }}
            ${{ steps.generate_tags.outputs.ghcr_image_latest || '' }}
            ${{ steps.generate_tags.outputs.docker_image_tag || '' }}
            ${{ steps.generate_tags.outputs.docker_image_latest || '' }}
